%{
  configs: [
    %{
      name: "default",
      files: %{
        included: [
          "lib/",
          "src/",
          "test/",
          "web/",
          "apps/*/lib/",
          "apps/*/src/",
          "apps/*/test/",
          "apps/*/web/"
        ],
        excluded: [~r"/_build/", ~r"/deps/", ~r"/node_modules/"]
      },
      strict: true,
      checks: [
        # {Credo.Check.Consistency.ExceptionNames, []},
        # {Credo.Check.Consistency.LineEndings, []},
        {Credo.Check.Consistency.MultiAliasImportRequireUse, []},
        # {Credo.Check.Consistency.ParameterPatternMatching, []},
        # {Credo.Check.Consistency.SpaceAroundOperators, []},
        # {Credo.Check.Consistency.SpaceInParentheses, []},
        # {Credo.Check.Consistency.TabsOrSpaces, []},
        {Credo.Check.Design.AliasUsage, false},
        # {Credo.Check.Design.TagFIXME, []},
        # {Credo.Check.Design.TagTODO, [exit_status: 2]},
        # {Credo.Check.Readability.AliasOrder, []},
        # {Credo.Check.Readability.BlockPipe, []},
        # {Credo.Check.Readability.FunctionNames, []},
        # {Credo.Check.Readability.ImplTrue, []},
        # {Credo.Check.Readability.LargeNumbers, []},
        # {Credo.Check.Readability.MaxLineLength, [priority: :low, max_length: 120]},
        # {Credo.Check.Readability.ModuleAttributeNames, []},
        {Credo.Check.Readability.ModuleDoc, false},
        # {Credo.Check.Readability.ModuleNames, []},
        {Credo.Check.Readability.MultiAlias, []},
        # {Credo.Check.Readability.ParenthesesInCondition, []},
        {Credo.Check.Readability.ParenthesesOnZeroArityDefs, parens: true},
        # {Credo.Check.Readability.PipeIntoAnonymousFunctions, []},
        # {Credo.Check.Readability.PredicateFunctionNames, []},
        # {Credo.Check.Readability.PreferImplicitTry, []},
        # {Credo.Check.Readability.RedundantBlankLines, []},
        # {Credo.Check.Readability.Semicolons, []},
        # {Credo.Check.Readability.SeparateAliasRequire, []},
        # {Credo.Check.Readability.SpaceAfterCommas, []},
        {Credo.Check.Readability.StrictModuleLayout, []},
        # {Credo.Check.Readability.StringSigils, []},
        # {Credo.Check.Readability.TrailingBlankLine, []},
        # {Credo.Check.Readability.TrailingWhiteSpace, []},
        # {Credo.Check.Readability.UnnecessaryAliasExpansion, []},
        # {Credo.Check.Readability.VariableNames, []},
        # {Credo.Check.Readability.WithCustomTaggedTuple, []},
        # {Credo.Check.Readability.WithSingleClause, []},
        # {Credo.Check.Refactor.Apply, []},
        # {Credo.Check.Refactor.CondStatements, []},
        # {Credo.Check.Refactor.CyclomaticComplexity, []},
        # {Credo.Check.Refactor.DoubleBooleanNegation, []},
        # {Credo.Check.Refactor.FilterFilter, []},
        # {Credo.Check.Refactor.FunctionArity, []},
        # {Credo.Check.Refactor.IoPuts, []},
        # {Credo.Check.Refactor.LongQuoteBlocks, []},
        # {Credo.Check.Refactor.MapJoin, []},
        # {Credo.Check.Refactor.MatchInCondition, []},
        # {Credo.Check.Refactor.NegatedConditionsInUnless, []},
        # {Credo.Check.Refactor.NegatedConditionsWithElse, []},
        # {Credo.Check.Refactor.Nesting, []},
        # {Credo.Check.Refactor.RedundantWithClauseResult, []},
        # {Credo.Check.Refactor.RejectReject, []},
        # {Credo.Check.Refactor.UnlessWithElse, []},
        # {Credo.Check.Refactor.WithClauses, []},
        # {Credo.Check.Warning.ApplicationConfigInModuleAttribute, []},
        # {Credo.Check.Warning.BoolOperationOnSameValues, []},
        # {Credo.Check.Warning.ExpensiveEmptyEnumCheck, []},
        # {Credo.Check.Warning.IExPry, []},
        # {Credo.Check.Warning.IoInspect, []},
        # {Credo.Check.Warning.OperationOnSameValues, []},
        # {Credo.Check.Warning.OperationWithConstantResult, []},
        # {Credo.Check.Warning.RaiseInsideRescue, []},
        # {Credo.Check.Warning.SpecWithStruct, []},
        # {Credo.Check.Warning.UnsafeExec, []},
        # {Credo.Check.Warning.UnusedEnumOperation, []},
        # {Credo.Check.Warning.UnusedFileOperation, []},
        # {Credo.Check.Warning.UnusedKeywordOperation, []},
        # {Credo.Check.Warning.UnusedListOperation, []},
        # {Credo.Check.Warning.UnusedPathOperation, []},
        # {Credo.Check.Warning.UnusedRegexOperation, []},
        # {Credo.Check.Warning.UnusedStringOperation, []},
        # {Credo.Check.Warning.UnusedTupleOperation, []},
        # {Credo.Check.Warning.WrongTestFileExtension, []}
        {Credo.Check.Readability.NestedFunctionCalls, false},
        {Credo.Check.Readability.SingleFunctionToBlockPipe, false},
        {Credo.Check.Readability.SinglePipe, false},
        {Credo.Check.Readability.Specs, false},
        {Credo.Check.Refactor.ABCSize, false},
        {Credo.Check.Refactor.AppendSingleItem, false},
        {Credo.Check.Refactor.FilterReject, false},
        {Credo.Check.Refactor.MapMap, false},
        {Credo.Check.Refactor.ModuleDependencies, false},
        {Credo.Check.Refactor.NegatedIsNil, false},
        {Credo.Check.Refactor.PipeChainStart, false},
        {Credo.Check.Refactor.RejectFilter, false},
        {Credo.Check.Refactor.VariableRebinding, false},
        {Credo.Check.Warning.LazyLogging, false},
        {Credo.Check.Warning.LeakyEnvironment, false},
        {Credo.Check.Warning.MapGetUnsafePass, false},
        {Credo.Check.Warning.MixEnv, false},
        {Credo.Check.Warning.UnsafeToAtom, false},
        {Credo.Check.Refactor.MapInto, false}
      ]
    }
  ]
}
